// Constants for the app.
const TYPE_INCOME = 'TYPE_INCOME';
const TYPE_EXPENSE = 'TYPE_EXPENSE';

const CATEGORY_NEED = 'CATEGORY_NEED';
const CATEGORY_WANT = 'CATEGORY_WANT';
const CATEGORY_SAVE = 'CATEGORY_SAVE';
const EXPENSE_CATEGORIES = [CATEGORY_NEED, CATEGORY_WANT, CATEGORY_SAVE];

export {TYPE_INCOME, TYPE_EXPENSE, CATEGORY_NEED, CATEGORY_WANT, CATEGORY_SAVE, EXPENSE_CATEGORIES};
