// Constants for the app.
const TYPE_INCOME = 'TYPE_INCOME';
const TYPE_EXPENSE = 'TYPE_EXPENSE';

const CATEGORY_NEED = 'CATEGORY_NEED';
const CATEGORY_WANT = 'CATEGORY_WANT';
const CATEGORY_SAVE = 'CATEGORY_SAVE';
const EXPENSE_CATEGORIES = [CATEGORY_NEED, CATEGORY_WANT, CATEGORY_SAVE];

// Recurring item kinds, as stored.
const RECURRING_KINDS = ['need', 'want', 'income'];

export {
  TYPE_INCOME,
  TYPE_EXPENSE,
  CATEGORY_NEED,
  CATEGORY_WANT,
  CATEGORY_SAVE,
  EXPENSE_CATEGORIES,
  RECURRING_KINDS,
};
